(() => {
  'use strict';
  const E=window.NumericEngine, original=E.clone(window.NUMERIC_DATA), $=id=>document.getElementById(id), colors={'绿':'#7cbb8d','蓝':'#78b6ee','紫':'#c795e3','金':'#e6bd6e'};
  let data=E.clone(original),state,mode=localStorage.getItem('music-notes-v03-mode')||'test',history=[],future=[],dragId=null,previousTotal=null,rewardFolded=false,toastTimer,pointerDrag=null,suppressClickUntil=0,rewardSelection=null,rewardIndex=null,stagePlaying=false;
  const key=m=>'music-notes-v03-state-'+m;
  try{const saved=JSON.parse(localStorage.getItem('music-notes-v03-config'));if(saved){if(saved.rules?.initialRows===3&&[2,3].includes(saved.rules?.initialCols)){saved.rules.initialCols=3;saved.rules.initialRows=2;}validateData(saved);data=saved;data.items.forEach(i=>i.icon=original.items.find(o=>o.id===i.id).icon);}}catch{}
  function validateData(d){
 if(d.version!==original.version||d.items?.length!==45||d.rules?.rows!==7||d.rules?.cols!==7)throw Error('须使用本版45件道具、7×7棋盘配置');
 const ids=new Set();for(const i of d.items){const src=original.items.find(x=>x.id===i.id);if(!src||ids.has(i.id)||i.base?.length!==6||i.effect?.length!==6||[...i.base,...i.effect].some(n=>!Number.isFinite(n)||n<0))throw Error('道具ID或六级数值无效');ids.add(i.id);for(const k of ['name','category','quality','width','height','area'])if(i[k]!==src[k])throw Error('名称、种类、品质、形状须与本版一致');if(JSON.stringify(i.tags)!==JSON.stringify(src.tags))throw Error('标签不可修改');if(i.category==='乐谱'&&i.base.some(n=>n!==0))throw Error('乐谱不提供基础值');if(['J03'].includes(i.id)&&i.effect.some(n=>!Number.isInteger(n)))throw Error('音符数量须为整数');if(['H02','J01'].includes(i.id)&&i.effect.some(n=>n>100))throw Error('概率不能超过100%');if(i.id==='R01'&&i.effect.some(n=>n>10))throw Error('高潮时长不能超过10秒');}
 const r=d.rules;for(const k of ['drawStamina','unlockStamina','unlockCells','advancedEvery','duplicatesPerLevel','surgeThreshold'])if(!Number.isInteger(r[k])||r[k]<1)throw Error(k+'须为正整数');for(const k of ['initialStamina','staminaCap','recoverAmount'])if(!Number.isInteger(r[k])||r[k]<0)throw Error(k+'无效');if(r.maxLevel!==6||r.initialRows!==2||r.initialCols!==3)throw Error('初始2行×3列、最高6级');if(!Number.isFinite(r.duration)||r.duration<1||r.duration>60||!Number.isFinite(r.noteInterval)||r.noteInterval<.1||r.noteInterval>2||!Number.isFinite(r.noteDivisor)||r.noteDivisor<=0)throw Error('时长1～60秒、间隔0.1～2秒、除数须大于0');
 const weights=(a,n)=>Array.isArray(a)&&a.length===n&&a.every(x=>Number.isFinite(x)&&x>=0)&&a.reduce((a,b)=>a+b,0)>0;
 for(const k of ['normalWeights','advancedWeights'])if(!weights(r[k],4))throw Error('抽奖权重须为四个非负数');if(typeof r.sameQualityDraw!=='boolean')throw Error('同品质开关须为布尔值');for(const q of E.qualities)if(!weights(r.noteWeights?.[q],5))throw Error('音符概率须包含五品质');if(!weights(r.noteScores,5))throw Error('音符基础分无效');
}

  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num=n=>Number(n).toLocaleString('zh-CN',{maximumFractionDigits:3}),pct=n=>num(n*100)+'%';
  const item=id=>data.items.find(i=>i.id===id), snapshot=()=>E.clone(state);
  function effectDescription(i,level=1){return i.description.replaceAll('X',num(i.effect[level-1]));}

  function toast(s){$('toast').textContent=s;$('toast').style.opacity=1;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').style.opacity=0,2600);}
  function save(){localStorage.setItem(key(mode),JSON.stringify(state));localStorage.setItem('music-notes-v03-mode',mode);localStorage.setItem('music-notes-v03-config',JSON.stringify(data));}
  function loadMode(next){mode=next;try{state=JSON.parse(localStorage.getItem(key(mode)));if(!state||state.version!==data.version)throw Error();for(const [id,o] of Object.entries(state.owned))if(!item(id)||o.level<1||o.level>6)throw Error();}catch{state=E.newState(data,mode);}if(state.spent===0&&state.unlocked.length===6&&[16,17,23,24,30,31].every(c=>state.unlocked.includes(c))){const test={...state,unlocked:E.initialCells(data.rules)};if(state.placed.every(p=>E.validPlacement(test,data,p.id,p.x,p.y)))state.unlocked=test.unlocked;}history=[];future=[];previousTotal=null;rewardFolded=false;render();}
  function checkpoint(){history.push(snapshot());if(history.length>60)history.shift();future=[];}
  function locked(){if(stagePlaying){toast('请先完成表演');return true;}if(state.drawQueue.length){toast('请先完成三选一');return true;}return false;}
  function image(i,cls=''){return `<img class="prop-icon ${cls}" src="${esc(i.icon)}" alt="${esc(i.name)}" draggable="false">`;}
  function footprint(i){return `<span class="footprint" role="img" aria-label="占格预览：${i.width}列${i.height}行，共${i.width*i.height}格" title="${i.width}列 × ${i.height}行，共${i.width*i.height}格，不可旋转" style="--cols:${i.width};--rows:${i.height}">${'<i></i>'.repeat(i.width*i.height)}</span>`;}
  function render(){if(E.autoUnlock(state,data).length){history=[];future=[];}document.querySelector('.unlock-input').style.display=mode==='test'?'':'none';const p=E.score(state,data);document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));
    $('metrics').innerHTML=[['剩余体力',num(state.stamina),`已消耗 ${state.spent}`],['累计表演值',num(state.scoreSum),`${state.shows} 场`],['开放格子',state.unlocked.length+'/49','系统随机扩格'],['抽奖次数',state.drawCount,`待选 ${state.drawQueue.length} 次`],['已拥有道具',Object.keys(state.owned).length+'/45',mode==='test'?'自由验证':'成长体验'],['累计效率',num(state.spent?state.scoreSum/state.spent:0),'分/体力']].map(([a,b,c])=>`<div class="metric"><span>${a}</span><strong>${b}</strong><small>${c}</small></div>`).join('');
    $('score').textContent=num(p.total);$('delta').textContent=previousTotal!==null&&p.total!==previousTotal?`本次变化 ${p.total-previousTotal>0?'+':''}${num(p.total-previousTotal)}`:'';
    $('breakdown').innerHTML=[['基础演奏值',p.base],['布局增益',p.ability],['产音格数',state.placed.filter(q=>item(q.id).category!=='乐谱').reduce((n,q)=>n+item(q.id).area,0)]].map(([a,b])=>`<span>${a}<b>${typeof b==='number'?num(b):b}</b></span>`).join('');
    $('unlockCount').value=state.unlocked.length;const occupied=state.placed.reduce((a,q)=>a+item(q.id).width*item(q.id).height,0);$('spaceSummary').textContent=`已放 ${state.placed.length} 件 · 占用 ${occupied} / ${state.unlocked.length} 格 · 系统自动扩格`;
    $('sets').innerHTML=['古典','流行','华丽','摇滚','爵士'].map(name=>`<button class="set-pill" data-set="${name}">${name} ${state.placed.filter(p=>item(p.id).primary===name).length}件</button>`).join('');
    $('sets').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('setFilter').value=b.dataset.set;renderInventory();});
    renderBoard(p);renderInventory();renderDetail(p);
    $('drawProgress').innerHTML=`抽奖体力 ${state.drawRemainder}/${data.rules.drawStamina} · 第${state.drawCount+1}次${(state.drawCount+1)%data.rules.advancedEvery===0?'高级':'普通'}<progress max="${data.rules.drawStamina}" value="${state.drawRemainder}"></progress>`;
    const full=state.unlocked.length+state.unlockCredits>=49;$('unlockProgress').innerHTML=`${full?'已全部解锁':`扩格体力 ${state.unlockRemainder}/${data.rules.unlockStamina} · 下次随机解锁${data.rules.unlockCells}格`}<progress max="${data.rules.unlockStamina}" value="${full?data.rules.unlockStamina:state.unlockRemainder}"></progress>`;
    $('perform').disabled=state.drawQueue.length>0;$('undo').disabled=!history.length||state.drawQueue.length>0;$('redo').disabled=!future.length||state.drawQueue.length>0;
    $('resumeReward').hidden=!state.drawQueue.length||!rewardFolded;renderReward();save();
  }
  function setText(s){return s.name+'兼容道具；流派仅用于设计分类，不按件数提供套装加成';}

  function renderBoard(p){const b=$('board');b.innerHTML='';const selected=p.info[state.selected];
    for(let c=0;c<49;c++){const open=state.unlocked.includes(c),can=false;const el=document.createElement('button');el.className=`cell ${open?'open':''} ${can?'expandable':''}`;el.style.gridColumn=String(c%7+1);el.style.gridRow=String(Math.floor(c/7)+1);el.dataset.cell=c;el.textContent=open?'':can?'+':'·';el.title=`第${Math.floor(c/7)+1}行，第${c%7+1}列${open?'':can?'：点击解锁':'：锁定'}`;el.onclick=()=>{if(!open){toast('累计消耗体力后，系统随机解锁相邻格子');}else if(state.selected)place(state.selected,c%7,Math.floor(c/7));};b.append(el);}
    for(const q of state.placed){const i=item(q.id),v=p.info[q.id],el=document.createElement('button');el.className=`piece ${state.selected===q.id?'selected':''} ${selected?.matches.includes(q.id)?'source-match':''} ${selected?.targets.includes(q.id)?'effect-target':''}`;el.dataset.id=q.id;el.style.setProperty('--quality',colors[i.quality]);el.style.gridColumn=`${q.x+1} / span ${i.width}`;el.style.gridRow=`${q.y+1} / span ${i.height}`;el.draggable=false;el.innerHTML=image(i)+footprint(i)+`<span class="label"><span>${i.name}</span><b>${num(v.total)}</b></span>`;el.title=`${i.name} ${state.owned[i.id].level}级 · ${i.width}×${i.height} · Ctrl点击卸下`;el.onclick=e=>{if(e.ctrlKey)unplace(q.id);else{state.selected=q.id;render();}};el.onpointerdown=e=>beginDrag(e,q.id,el);el.ondragstart=e=>e.preventDefault();b.append(el);}
  }
  function beginDrag(e,id,source){if(e.button!==0||e.ctrlKey||pointerDrag)return;pointerDrag={id,source,pointerId:e.pointerId,startX:e.clientX,startY:e.clientY,started:false,ghost:null,candidate:null};source.setPointerCapture?.(e.pointerId);document.addEventListener('pointermove',moveDrag);document.addEventListener('pointerup',endDrag);document.addEventListener('pointercancel',cancelDrag);}
  function moveDrag(e){const d=pointerDrag;if(!d||d.pointerId!==e.pointerId)return;if(!d.started){if(Math.hypot(e.clientX-d.startX,e.clientY-d.startY)<5)return;if(locked()){cancelDrag();return;}d.started=true;dragId=d.id;state.selected=d.id;const i=item(d.id),cell=$('board').querySelector('.cell').getBoundingClientRect(),gap=parseFloat(getComputedStyle($('board')).columnGap)||0;d.ghost=document.createElement('div');d.ghost.className='drag-preview pointer-ghost';d.ghost.style.cssText=`width:${cell.width*i.width+gap*(i.width-1)}px;height:${cell.height*i.height+gap*(i.height-1)}px;--quality:${colors[i.quality]};--cols:${i.width};--rows:${i.height};--gap:${gap}px`;d.ghost.innerHTML=`<span class="drag-grid">${'<i></i>'.repeat(i.width*i.height)}</span>${image(i)}<span class="drag-name">${i.name} · ${i.width}×${i.height}</span>`;document.body.append(d.ghost);d.source.classList.add('dragging-source');}e.preventDefault();updateDrag(e.clientX,e.clientY);}
  function updateDrag(clientX,clientY){const d=pointerDrag,i=item(d.id),board=$('board'),r=board.getBoundingClientRect(),cell=board.querySelector('.cell').getBoundingClientRect(),gap=parseFloat(getComputedStyle(board).columnGap)||0;d.ghost.style.transform=`translate(${clientX}px,${clientY}px)`;clearDrop();d.candidate=null;const over=clientX>=cell.left&&clientX<r.right&&clientY>=cell.top&&clientY<r.bottom;if(over){const x=Math.floor((clientX-cell.left)/(cell.width+gap)),y=Math.floor((clientY-cell.top)/(cell.height+gap));const verdict=E.placement(state,data,d.id,x,y),valid=verdict.valid;d.candidate={x,y,...verdict};if(valid)previewDragEffects(d.id,x,y,verdict.swapId);for(let dy=0;dy<i.height;dy++)for(let dx=0;dx<i.width;dx++){if(x+dx>=0&&x+dx<7&&y+dy>=0&&y+dy<7)board.querySelector(`[data-cell="${(y+dy)*7+x+dx}"]`)?.classList.add(valid?'drop-ok':'drop-bad');}d.ghost.classList.toggle('invalid',!valid);d.ghost.classList.toggle('swap',valid&&!!verdict.swapId);d.ghost.querySelector('.drag-name').textContent=verdict.swapId&&valid?`替换${item(verdict.swapId).name} → 回仓`:i.name+' · '+i.width+'×'+i.height;}else{const w=document.querySelector('.inventory-panel').getBoundingClientRect(),returning=state.placed.some(p=>p.id===d.id)&&clientX>=w.left&&clientX<w.right&&clientY>=w.top&&clientY<w.bottom;d.candidate=returning?{warehouse:true}:null;document.querySelector('.inventory-panel').classList.toggle('drop-active',returning);d.ghost.classList.toggle('invalid',!returning);}}
  function endDrag(e){const d=pointerDrag;if(!d||d.pointerId!==e.pointerId)return;if(d.started){updateDrag(e.clientX,e.clientY);const candidate=d.candidate;cleanupDrag();suppressClickUntil=Date.now()+350;if(candidate?.warehouse)unplace(d.id);else if(candidate?.valid)place(d.id,candidate.x,candidate.y);else toast('未放入有效空格，道具保留原位置');}else cleanupDrag();}
  function cleanupDrag(){const d=pointerDrag;pointerDrag=null;document.removeEventListener('pointermove',moveDrag);document.removeEventListener('pointerup',endDrag);document.removeEventListener('pointercancel',cancelDrag);if(d?.source.hasPointerCapture?.(d.pointerId))d.source.releasePointerCapture(d.pointerId);d?.source.classList.remove('dragging-source');d?.ghost?.remove();document.querySelector('.inventory-panel').classList.remove('drop-active');clearDrop();dragId=null;}
  function cancelDrag(){if(pointerDrag?.started)suppressClickUntil=Date.now()+350;cleanupDrag();}
  document.addEventListener('click',e=>{if(Date.now()<suppressClickUntil){e.preventDefault();e.stopImmediatePropagation();}},true);
  window.addEventListener('blur',cancelDrag);
  function clearDrop(){document.querySelectorAll('.drop-ok,.drop-bad,.drag-target,.drag-source').forEach(e=>e.classList.remove('drop-ok','drop-bad','drag-target','drag-source'));}
  function place(id,x,y){if(!id||!state.owned[id]||locked())return;const verdict=E.placement(state,data,id,x,y);if(!verdict.valid){toast('无法放置：越界、未解锁或同时覆盖多件道具');return;}checkpoint();previousTotal=E.score(state,data).total;state.placed=state.placed.filter(p=>p.id!==id&&p.id!==verdict.swapId);state.placed.push({id,x,y});state.selected=id;render();if(verdict.swapId)toast(item(verdict.swapId).name+'已回仓');}
  function unplace(id){if(locked())return;checkpoint();previousTotal=E.score(state,data).total;state.placed=state.placed.filter(p=>p.id!==id);render();}
  function autoPlace(id){for(let y=0;y<7;y++)for(let x=0;x<7;x++)if(E.validPlacement(state,data,id,x,y)){place(id,x,y);return;}toast('没有足够的连续空间；道具不可旋转');}
  function renderInventory(){const query=$('search').value.trim(),quality=$('quality').value,category=$('category').value,set=$('setFilter').value;const filtered=data.items.filter(i=>(state.owned[i.id]||mode==='test')&&(!query||[i.name,i.id,i.category,i.song].join(' ').includes(query))&&(!quality||i.quality===quality)&&(!category||i.category===category)&&(!set||(set==='通用'?i.primary==='通用':i.primary===set)));
    $('inventorySummary').textContent=`${Object.keys(state.owned).length} 件已拥有 · 选中后拖放或点击格子`;
    $('inventory').innerHTML=filtered.map(i=>`<button class="inventory-item ${state.selected===i.id?'selected':''}" style="--quality:${colors[i.quality]}" data-id="${i.id}" draggable="false">${image(i)}<span><strong>${i.name}${state.placed.some(p=>p.id===i.id)?' <span class="placed-check" role="img" aria-label="已放入背包" title="已放入背包">✓</span>':''}</strong><small>${i.quality} · ${i.width}×${i.height} · ${state.owned[i.id]?.level||1}级</small><small>${i.category}${i.song?' / '+i.song:''}</small>${footprint(i)}</span></button>`).join('')||'<p class="hint">没有符合条件的道具</p>';
    $('inventory').querySelectorAll('[data-id]').forEach(b=>{b.onclick=e=>{state.selected=b.dataset.id;if(e.ctrlKey)autoPlace(state.selected);else render();};b.onpointerdown=e=>beginDrag(e,b.dataset.id,b);b.ondragstart=e=>e.preventDefault();});
  }
  function renderDetail(p){const i=item(state.selected);if(!i){$('detail').innerHTML='<p>选择道具，查看每级数值、计数来源和受益目标。</p>';return;}const o=state.owned[i.id],level=o?.level||1,v=p.info[i.id];const description=effectDescription(i,level);
    $('detail').innerHTML=`<div class="detail-head"><h3>${i.name}</h3>${footprint(i)}<span style="color:${colors[i.quality]}">${i.quality} · ${i.width}×${i.height} · 不可旋转</span></div><p>${esc(description).replaceAll('a点',num(i.effect[E.tierIndex(level)])+'点').replaceAll('a%',pct(i.effect[E.tierIndex(level)]))}</p><div class="numbers">${i.base.map((b,j)=>`<div class="${level===j+1?'current':''}"><small>${j+1}级</small><b>${num(b)}</b></div>`).join('')}</div><p>效果参数（1～6级）：${i.effect.map(n=>i.category==='装扮'?pct(n):num(n)).join(' / ')} · ${i.param}</p>${i.notes.length?`<div class="note">${i.notes.map(esc).join('；')}</div>`:''}${v?`<div class="formula">本件演奏值：${v.base} + 布局增益 ${num(v.ability)} = ${num(v.total)}</div><div class="sources">条件计数：${v.count}；${v.active?'布局增益已生效':'事件效果请看表演结果'}<br>匹配来源：${v.matches.map(id=>item(id).name).join('、')||'无'}<br>受益目标：${v.targets.map(id=>item(id).name).join('、')||'背包／资源或无'}<br>${v.sources.map(s=>`${s.type} · ${s.name} +${num(s.value)}`).join('<br>')}</div>`:'<p>当前在仓库，不参与任何结算。</p>'}<div class="detail-actions">${mode==='test'?`<label>测试等级 <select id="level">${[1,2,3,4,5,6].map(n=>`<option ${level===n?'selected':''}>${n}</option>`).join('')}</select></label>`:`<span>升级进度 ${o?.progress||0}/${data.rules.duplicatesPerLevel}</span>`}<button id="quickPlace">${v?'卸回仓库':'自动找空位'}</button><button id="editItem">调整测试数值</button></div><p class="hint">来源：${i.source}；青色为条件来源，绿色为受益目标。</p>`;
    const preview=document.createElement('div');preview.className='detail-preview';preview.innerHTML=image(i);$('detail').querySelector('.detail-head').after(preview);const actionBar=$('detail').querySelector('.detail-actions');$('detail').querySelector('.detail-head').after(actionBar);
    if($('level'))$('level').onchange=e=>{if(locked())return;checkpoint();previousTotal=p.total;o.level=Number(e.target.value);o.progress=0;render();};$('quickPlace').onclick=()=>v?unplace(i.id):autoPlace(i.id);$('editItem').onclick=()=>editItem(i.id);
  }
  function modal(title,html){$('modalTitle').textContent=title;$('modalContent').innerHTML=html;if(!$('modal').open)$('modal').showModal();}
  function editItem(id){if(locked())return;const i=item(id);modal('调整测试数值 · '+i.name,`<p>只修改本机数值版；原始Excel不变。保存后立即重算。</p><h3>各级基础演奏值</h3><div class="form-grid">${i.base.map((n,j)=>`<label>${j+1}级<input id="base${j}" type="number" min="0" step="any" value="${n}"></label>`).join('')}</div><h3>实际效果</h3><div class="form-grid">${i.effect.map((n,j)=>`<label>${j+1}级${i.category==='装扮'?'（小数比例）':''}<input id="effect${j}" type="number" min="0" step="any" value="${n}"></label>`).join('')}</div><p class="hint">六级分别生效。单位：${i.param}；未成长的条件保持不变。</p><button class="primary" id="saveItem">保存并重算</button>`);$('saveItem').onclick=()=>{const base=i.base.map((_,j)=>Number($('base'+j).value)),effect=i.effect.map((_,j)=>Number($('effect'+j).value));if([...base,...effect].some(x=>!Number.isFinite(x)||x<0)){toast('请输入非负数');return;}const candidate=E.clone(data);candidate.items.find(x=>x.id===id).base=base;candidate.items.find(x=>x.id===id).effect=effect;try{validateData(candidate);}catch(e){toast(e.message);return;}i.base=base;i.effect=effect;i.notes=['当前使用手动测试值'];history=[];future=[];$('modal').close();render();};}
  function renderReward(){const q=state.drawQueue[0];if(q?.index!==rewardIndex){rewardSelection=null;rewardIndex=q?.index;}if(!q){if($('reward').open)$('reward').close();$('resumeReward').hidden=true;return;}if(rewardFolded)return;
    $('rewardTitle').textContent=`第${q.index}次 · ${q.advanced?'高级':'普通'}三选一`;$('rewardSummary').textContent=`剩余${state.drawQueue.length}次待选 · 背包已开放${state.unlocked.length}格 · 绿/蓝/紫/金权重：${(q.advanced?data.rules.advancedWeights:data.rules.normalWeights).join('/')} · ${data.rules.sameQualityDraw?'本组同品质':'各选项独立品质'}`;
    $('choices').innerHTML=q.choices.map(id=>{const i=item(id),o=state.owned[id];return `<button class="choice ${rewardSelection===id?'selected':''}" aria-pressed="${rewardSelection===id}" data-id="${id}" style="--quality:${colors[i.quality]}">${image(i)}<div>${footprint(i)}<h3>${i.name}</h3><small>${i.quality} · ${i.width}×${i.height} · ${i.category}</small><small>${i.song||'通用支持'}</small><p>${esc(effectDescription(i,o?.level||1))}</p><small>${o?o.level===6?'已满级；本次不增加等级':`已拥有${o.level}级 · 获得后增加1份升级进度`:'新道具 · 1级'}</small></div></button>`;}).join('');$('choices').querySelectorAll('button').forEach(b=>b.onclick=()=>{rewardSelection=b.dataset.id;renderReward();});$('confirmReward').disabled=!rewardSelection;$('rewardSelection').textContent=rewardSelection?'已选：'+item(rewardSelection).name:'请选择一件道具';$('confirmReward').onclick=()=>{if(!rewardSelection)return;const id=rewardSelection,msg=E.choose(state,data,id);state.selected=id;history=[];future=[];toast(item(id).name+'：'+msg);render();};if(!$('reward').open)$('reward').showModal();
  }
  function showResult(result){modal('本场音符结算',`<div class="score" style="text-align:left"><strong>${num(result.total)}</strong><span>最终表演值 · 音符加成 ${pct(result.rate)}</span></div><div class="formula">${esc(result.formula)}</div><p>${result.regular} 基础＋${result.additional}追加＝${result.totalNotes}枚存活音符 · 四分${result.quarter} / 八分${result.eighth} · 交换消耗${result.consumed}枚原音符 · G=${result.G}格 · N=${num(result.N)}</p><h3>来源贡献</h3><table><tr><th>道具</th><th>基础 / 追加</th><th>四分 / 八分 / 消耗</th><th>绿 蓝 紫 金 红</th><th>变色</th><th>音符分</th></tr>${Object.values(result.stats).map(s=>`<tr><td>${s.name}</td><td>${s.regular} / ${s.additional}</td><td>${s.quarter} / ${s.eighth} / ${s.consumed}</td><td>${s.qualities.join(' / ')}</td><td>${s.changed}</td><td>${num(s.score)}</td></tr>`).join('')}</table><h3>效果触发计数</h3><p>${Object.entries(result.effects).map(([id,n])=>`${item(id).name}：${n}`).join('；')||'本场无事件效果触发'}</p><p class="hint">计数表示各效果的应用次数，不可直接比较强弱；布局增益见道具详情。</p><h3>事件与时间窗口</h3><p>${result.events.map(e=>`${num(e.time)}秒 ${e.type}：${e.detail}`).join('<br>')||'无高潮或Solo'}</p><table><tr><th>秒</th><th>累计音符</th><th>累计音符分</th><th>本秒追加</th></tr>${result.timeline.map(s=>`<tr><td>${s.time}</td><td>${s.notes}</td><td>${num(s.score)}</td><td>${s.windowAdditional}</td></tr>`).join('')}</table><p>种子：${esc(result.seed)}。消耗体力只影响奖励进度，不倍乘本场分数。</p><button id="continueResult" class="primary">继续${state.drawQueue.length?'三选一':'配置'}</button>`);$('continueResult').onclick=()=>{$('modal').close();rewardFolded=false;render();};}

  async function perform(){if(locked())return;if(!state.placed.length){toast('请先放入道具');return;}try{const amount=Number($('cost').value);if(!Number.isInteger(amount)||amount<=0||amount>state.stamina)throw Error('体力不足或消耗值无效');const result=E.performance(state,data,{seed:`${state.seed}:show:${state.shows+1}`});if(!$('skipStage').checked){stagePlaying=true;const ok=await playStage(result);stagePlaying=false;if(!ok){toast('已取消，未消耗体力');return;}}E.spend(state,data,amount);state.shows++;state.scoreSum+=result.total;state.logs.unshift({...result,number:state.shows,stamina:amount,spent:state.spent});if(state.logs.length>100)state.logs.pop();history=[];future=[];rewardFolded=true;render();showResult(result);}catch(e){stagePlaying=false;toast(e.message);}}

  function tools(){if(locked())return;modal('参数与规则',`<p>09/27五流派候选V0.3；参数只保存在本机，可导出共享。默认独立抽品质，支持对比同品质候选。</p><div class="form-grid"><label>剩余体力<input id="editStamina" type="number" min="0" value="${state.stamina}"></label><label>可复现种子<input id="editSeed" value="${esc(state.seed)}"></label><label>音符转化除数<input id="noteDivisor" type="number" value="${data.rules.noteDivisor}"></label><label>单场秒数<input id="duration" type="number" value="${data.rules.duration}"></label><label>高潮数量阈值<input id="surgeThreshold" type="number" value="${data.rules.surgeThreshold}"></label><label>抽奖方式<select id="sameQualityDraw"><option value="false" ${!data.rules.sameQualityDraw?'selected':''}>每个选项独立品质</option><option value="true" ${data.rules.sameQualityDraw?'selected':''}>三个选项同品质</option></select></label></div><p><button id="saveTools" class="primary">保存参数</button> <button id="recover">模拟恢复30分钟体力</button> <button id="allCells">测试：开放全部49格</button></p><h3>已采用规则</h3><p>45件＝40乐器＋5乐谱，流派标签不提供套装加成。乐谱基础值为0，不常规产音。7×7棋盘，初始中央2行×3列，不可旋转。每5体力由系统随机解锁2格，每格均须与已开放区域上下左右相邻；每3体力一次三选一，每第7次高级。同名一份升一级，最高6级。</p><p>普通绿/蓝/紫/金=${data.rules.normalWeights.join('/')}；高级=${data.rules.advancedWeights.join('/')}（相对权重）。每级基础和效果均读独立配置。</p><p>同一时刻的全部基础音符合为一批：基础生成→基础转品→追加与复制→追加转品→计分。转品占用优先级：中音萨克斯→次中音萨克斯→黑管→鎏金竖琴→沙龙钢琴；概率失败也占用。四分系数1，八分0.75；八分不等于追加。</p><p>t=0不产音，t=10结算后结束。t=5基础批次先结算，再进入Solo，5.25/5.5/5.75/6秒各产生G枚紫色基础八分。仅非高潮非Solo的四分计入高潮阈值，交换消耗后计数；下一到点批次启动，弦乐/打击间隔减半并改八分。爵士伴奏仅读取基础轮实际随机变调，每秒上限窗口为(0,1]、(1,2]等。</p><p>演奏值在开场计算，百分比相加；音符固定加分在百分比之后。最终 floor(A×(1+N/除数))；不截断音符加成。旧手动合拍、魅力与套装公式已被新版设计替换。</p><p>测试设定：999体力、初始2行×3列、扩格5换2、恢复规则。成长模式初始给琵琶＋三角铁，仅作试用起点。每派6件主要乐器，另10绿通用与5蓝通用乐谱。27格布局含主流派6件＋通用乐器＋乐谱；49格混合示例不代表两个完整流派，不保证收益最优。</p><h3>案例与存档</h3><p>${Object.keys(data.presets).map(n=>`<button data-preset="${esc(n)}">${esc(n)}</button>`).join(' ')}</p><p><button id="exportState">导出布局与参数</button> <button id="importStateButton">载入布局与参数</button><input id="importState" type="file" accept=".json" hidden> <button id="resetMode">重置当前模式</button></p><p>案例进入自由验证。V0.3使用独立存档，旧版存档仍保留在浏览器中；旧模板不会覆盖新机制。</p>`);addTools();
 $('saveTools').onclick=()=>{try{const candidate=E.clone(data);for(const k of ['noteDivisor','duration','surgeThreshold'])candidate.rules[k]=Number($(k).value);candidate.rules.sameQualityDraw=$('sameQualityDraw').value==='true';validateData(candidate);const stamina=Number($('editStamina').value);if(!Number.isInteger(stamina)||stamina<0)throw Error('体力须为非负整数');data=candidate;state.stamina=stamina;state.seed=$('editSeed').value||'notes';history=[];future=[];$('modal').close();render();}catch(e){toast(e.message);}};
 $('recover').onclick=()=>{if(state.stamina<data.rules.staminaCap)state.stamina=Math.min(data.rules.staminaCap,state.stamina+data.rules.recoverAmount);$('editStamina').value=state.stamina;save();};$('allCells').onclick=()=>{if(mode!=='test'){toast('请先切换自由验证');return;}checkpoint();E.manualUnlock(state,data,49);$('modal').close();render();};
 $('exportState').onclick=()=>download('五流派-布局与参数.json',JSON.stringify({data,state},null,2),'application/json');$('importStateButton').onclick=()=>$('importState').click();$('importState').onchange=importState;$('resetMode').onclick=()=>{if(!confirm('重置当前模式？'))return;state=E.newState(data,mode);history=[];future=[];$('modal').close();render();};document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>preset(b.dataset.preset));toolTabs();}

  function toolTabs(){const content=$('modalContent'),children=[...content.children],panes=['模拟与Excel','参数','规则与流派','案例与存档'].map(()=>{const el=document.createElement('section');el.className='tool-pane';return el;});let target=1;for(const child of children){if(child.classList.contains('extra-tools')){panes[0].append(child);continue;}if(child.tagName==='H3'&&child.textContent==='已采用规则')target=2;if(child.tagName==='H3'&&child.textContent==='案例与存档')target=3;panes[target].append(child);}const tabs=document.createElement('nav');tabs.className='tool-tabs';['模拟与Excel','参数','规则与流派','案例与存档'].forEach((label,n)=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>{panes.forEach((p,i)=>p.hidden=i!==n);[...tabs.children].forEach((c,i)=>c.classList.toggle('active',i===n));};tabs.append(b);});content.append(tabs,...panes);tabs.children[1].click();}
  function previewDragEffects(id,x,y,swapId){const test=E.clone(state);test.placed=test.placed.filter(p=>p.id!==id&&p.id!==swapId);test.placed.push({id,x,y});const v=E.score(test,data).info[id];for(const p of $('board').querySelectorAll('.piece')){p.classList.toggle('drag-source',v.matches.includes(p.dataset.id));p.classList.toggle('drag-target',v.targets.includes(p.dataset.id));}}
  function playStage(plan){return new Promise(resolve=>{const d=document.createElement('dialog');d.className='live-stage';d.innerHTML='<div class="modal-top"><h2>音符表演回放</h2><button id="cancelStage">取消</button></div><p>按本场种子生成的实际事件回放；空格暂停 / 继续</p><div id="liveNotes"></div><progress id="liveProgress" max="'+data.rules.duration+'" value="0"></progress><p id="liveEvent"></p><div class="actions"><button id="stageSpeed">速度 ×1</button><button id="pauseStage">暂停</button><button id="skipRest">跳过剩余</button></div>';document.body.append(d);d.showModal();let frame,last=performance.now(),elapsed=0,speed=1,paused=false,done=false;const cleanup=ok=>{if(done)return;done=true;cancelAnimationFrame(frame);document.removeEventListener('keydown',key);d.remove();resolve(ok);};const get=id=>d.querySelector('#'+id);const pause=()=>{paused=!paused;get('pauseStage').textContent=paused?'继续':'暂停';};const key=e=>{if(e.code==='Space'){e.preventDefault();pause();}};document.addEventListener('keydown',key);get('pauseStage').onclick=pause;get('cancelStage').onclick=()=>cleanup(false);d.oncancel=e=>{e.preventDefault();cleanup(false);};get('skipRest').onclick=()=>cleanup(true);get('stageSpeed').onclick=()=>{speed=speed===1?2:1;get('stageSpeed').textContent='速度 ×'+speed;};const tick=now=>{if(done)return;if(!paused)elapsed+=Math.min(now-last,100)*speed/1000;last=now;get('liveProgress').value=elapsed;const s=plan.timeline.filter(x=>x.time<=elapsed).at(-1);get('liveNotes').innerHTML=`<strong>${num(s?.notes||0)} 枚音符</strong><p>${elapsed.toFixed(1)} / ${data.rules.duration}秒 · 累计音符分 ${num(s?.score||0)}</p>`;get('liveEvent').textContent=plan.events.filter(e=>e.time<=elapsed).at(-1)?.type||'常规出音';if(elapsed>=data.rules.duration){cleanup(true);return;}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);});}

  function addTools(){const extra=document.createElement('section');extra.className='extra-tools';extra.innerHTML=`<h3>批量模拟</h3><p>不消耗体力，不改变成长进度。同种子可复现。</p><div class="form-grid"><label>种子<input id="batchSeed" value="${esc(state.seed)}"></label><label>场次<input id="batchCount" type="number" min="1" max="1000" value="100"></label><label>每场体力（效率分母）<input id="batchCost" type="number" min="1" value="1"></label></div><p><button id="runBatch">运行模拟</button> <button data-count="1">1场</button> <button data-count="100">100场</button> <button data-count="1000">1000场</button> <button id="batchCsv" disabled>导出结果</button></p><div id="batchOutput"></div><h3>六级数值Excel</h3><p>仅接受V0.3的45件模板；旧版模板不能直接混入。规则、概率、基础值与六级效果均可调整。</p><button id="exportExcel">导出数值Excel</button> <button id="loadExcel">加载数值Excel</button><input id="excelFile" type="file" accept=".xlsx" hidden>`;$('modalContent').prepend(extra);let batch=[];
 $('runBatch').onclick=async()=>{try{const n=Number($('batchCount').value),cost=Number($('batchCost').value),seed=$('batchSeed').value;if(!Number.isInteger(n)||n<1||n>1000||!Number.isInteger(cost)||cost<1||!state.placed.length)throw Error('请摆放道具；场次1～1000，体力正整数');const button=$('runBatch'),output=$('batchOutput');button.disabled=true;batch=[];const ss=E.clone(state),dd=E.clone(data);for(let k=0;k<n;k++){const r=E.performance(ss,dd,{seed:`${seed}:batch:${k+1}`});batch.push({seed:r.seed,preview:r.preview,total:r.total,totalNotes:r.totalNotes,quarter:r.quarter,eighth:r.eighth,consumed:r.consumed,rate:r.rate,N:r.N});if(k%20===0){output.textContent=`正在模拟 ${k+1}/${n}`;await new Promise(resolve=>setTimeout(resolve,0));}}const vals=batch.map(r=>r.total).sort((a,b)=>a-b),sum=vals.reduce((a,b)=>a+b,0);output.textContent=`${n}场 · 均值 ${num(sum/n)} · 最低 ${vals[0]} · 最高 ${vals.at(-1)} · P50 ${vals[Math.floor((n-1)/2)]} · 效率 ${num(sum/n/cost)}分/体力`;button.disabled=false;const csv=extra.querySelector('#batchCsv');csv.disabled=false;}catch(e){toast(e.message);if($('runBatch'))$('runBatch').disabled=false;}};
 extra.querySelectorAll('[data-count]').forEach(b=>b.onclick=()=>{$('batchCount').value=b.dataset.count;$('runBatch').click();});$('batchCsv').onclick=()=>download('五流派-批量模拟.csv','种子,演奏值,总分,音符数,四分,八分,消耗原音符,音符加成,音符分\r\n'+batch.map(r=>[JSON.stringify(r.seed),r.preview,r.total,r.totalNotes,r.quarter,r.eighth,r.consumed,r.rate,r.N].join(',')).join('\r\n'),'text/csv');$('exportExcel').onclick=exportExcel;$('loadExcel').onclick=()=>$('excelFile').click();$('excelFile').onchange=loadExcel;}

  function exportExcel(){const wb=XLSX.utils.book_new(),add=(n,rows)=>XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows),n);add('道具',[['ID','名称',...Array.from({length:6},(_,i)=>`${i+1}级基础`),...Array.from({length:6},(_,i)=>`${i+1}级效果`),'参数单位','效果说明'],...data.items.map(i=>[i.id,i.name,...i.base,...i.effect,i.param,i.description])]);add('规则',[['字段','值(JSON格式)'],...Object.entries(data.rules).map(([k,v])=>[k,JSON.stringify(v)])]);add('版本',[[data.version]]);add('说明',[['09/27五流派候选V0.3；45件；每一级均独立'],['百分比参数填百分点，例如10代表10%；固定分与秒数按参数单位'],['形状、名称、类别、效果逻辑修改须同步代码；不得套用旧31件模板'],['音符品质顺序绿/蓝/紫/金/红；奖池品质顺序绿/蓝/紫/金']]);XLSX.writeFile(wb,'爱乐之城-五流派数值配置.xlsx');}

  async function loadExcel(e){try{if(!e.target.files[0])return;const wb=XLSX.read(await e.target.files[0].arrayBuffer(),{type:'array'}),candidate=readNumericWorkbook(wb);validateData(candidate);data=candidate;history=[];future=[];$('modal').close();render();toast('五流派数值已载入');}catch(e){toast('加载失败：'+e.message);}}

  function readNumericWorkbook(wb){if(!wb.Sheets['道具']||!wb.Sheets['规则']||wb.Sheets['版本']?.A1?.v!==data.version)throw Error('请使用本版导出的模板');const out=E.clone(data),rows=XLSX.utils.sheet_to_json(wb.Sheets['道具'],{header:1}).slice(1).filter(r=>r[0]),seen=new Set();if(rows.length!==45)throw Error('须含45件');for(const r of rows){const i=out.items.find(i=>i.id===r[0]);if(!i||seen.has(i.id)||i.name!==r[1])throw Error('ID/名称无效');seen.add(i.id);i.base=r.slice(2,8);i.effect=r.slice(8,14);i.notes=['当前使用Excel测试数值'];}const keys=new Set();for(const [k,v] of XLSX.utils.sheet_to_json(wb.Sheets['规则'],{header:1}).slice(1).filter(r=>r[0])){if(!(k in out.rules)||keys.has(k))throw Error('规则字段无效');keys.add(k);out.rules[k]=JSON.parse(String(v));}if(keys.size!==Object.keys(out.rules).length)throw Error('规则缺项');return out;}

  function preset(name){save();mode='test';state=E.newState(data,mode);state.unlocked=Array.from({length:49},(_,i)=>i);state.placed=E.clone(data.presets[name]);state.selected=state.placed[0]?.id;history=[];future=[];$('modal').close();render();}

  async function importState(e){try{const v=JSON.parse((await e.target.files[0].text()).replace(/^\uFEFF/,""));validateData(v.data);const st=v.state;if(!['trial','test'].includes(st.mode)||!Array.isArray(st.unlocked)||new Set(st.unlocked).size!==st.unlocked.length||st.unlocked.some(c=>!Number.isInteger(c)||c<0||c>=49))throw Error('存档棋盘无效');for(const [id,o] of Object.entries(st.owned))if(!v.data.items.some(i=>i.id===id)||!Number.isInteger(o.level)||o.level<1||o.level>6)throw Error('存档道具等级无效');const test={...st,placed:[]};for(const p of st.placed){if(!st.owned[p.id]||test.placed.some(q=>q.id===p.id)||!E.validPlacement(test,v.data,p.id,p.x,p.y))throw Error('摆放越界或重叠');test.placed.push(p);}if(st.drawQueue.length)throw Error('请使用已完成三选一的存档');if(!Number.isFinite(st.stamina)||st.stamina<0)throw Error('体力无效');v.data.items.forEach(i=>i.icon=original.items.find(o=>o.id===i.id).icon);data=v.data;state=st;mode=state.mode;history=[];future=[];$('modal').close();render();toast('布局与参数已载入');}catch(err){toast('载入失败：'+err.message);}}
  function download(name,text,type){const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
  function logs(){modal('音符表演日志',`<p><button id="csv">导出CSV</button></p><table><tr><th>场次</th><th>体力</th><th>A</th><th>常规/追加</th><th>N</th><th>加成</th><th>最终值</th><th>明细</th></tr>${state.logs.map((r,k)=>`<tr><td>${r.number}</td><td>${r.stamina}</td><td>${num(r.preview)}</td><td>${r.regular}/${r.additional}</td><td>${num(r.N)}</td><td>${pct(r.rate)}</td><td>${r.total}</td><td><button data-log="${k}">查看</button></td></tr>`).join('')}</table>`);document.querySelectorAll('[data-log]').forEach(b=>b.onclick=()=>showResult(state.logs[Number(b.dataset.log)]));$('csv').onclick=()=>download('五流派-表演日志.csv',[['场次','体力','演奏值A','基础','追加','四分','八分','消耗原音符','音符分N','音符加成','最终值','种子'],...state.logs.map(r=>[r.number,r.stamina,r.preview,r.regular,r.additional,r.quarter,r.eighth,r.consumed,r.N,r.rate,r.total,r.seed])].map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n'),'text/csv');}

  for(const scheme of ['A','B'])$('process'+scheme).onclick=()=>{if(locked())return;if(!state.placed.some(p=>item(p.id).category!=='乐谱')){toast('请先在背包放入至少一件乐器');return;}stagePlaying=true;try{window.ProcessTest.open({state:E.clone(state),data:E.clone(data),scheme,onClose:()=>{stagePlaying=false;}});}catch(e){stagePlaying=false;toast(e.message);}};
  $('tools').onclick=tools;$('logs').onclick=logs;$('perform').onclick=perform;$('closeModal').onclick=()=>{$('modal').close();if(state.drawQueue.length){rewardFolded=false;render();}};
  $('modal').addEventListener('cancel',()=>{setTimeout(()=>{if(state.drawQueue.length){rewardFolded=false;render();}},0);});
  $('foldReward').onclick=()=>{rewardFolded=true;$('reward').close();$('resumeReward').hidden=false;};$('reward').addEventListener('cancel',e=>{e.preventDefault();$('foldReward').click();});$('resumeReward').onclick=()=>{rewardFolded=false;render();};
  $('unload').onclick=()=>{if(locked())return;checkpoint();previousTotal=E.score(state,data).total;state.placed=[];render();};
  $('undo').onclick=()=>{if(!history.length||locked())return;future.push(snapshot());state=history.pop();render();};$('redo').onclick=()=>{if(!future.length||locked())return;history.push(snapshot());state=future.pop();render();};
  for(const id of ['search','quality','category','setFilter'])$(id).addEventListener('input',renderInventory);document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{if(state.drawQueue.length){toast('请先完成三选一后切换模式');return;}save();loadMode(b.dataset.mode);});
  $('icons').onclick=()=>modal('表演道具 PNG 资源',`<p>本版暂复用旧PNG作示意，多个候选可能共用图像；实际形状看占格网格。新道具尚未分配正式美术资源名。</p><div class="asset-grid">${data.items.map(i=>`<a href="${i.icon}" target="_blank" rel="noopener">${image(i)}${i.name}</a>`).join('')}</div>`);

  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&pointerDrag){e.preventDefault();cancelDrag();return;}if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)||$('modal').open||$('reward').open)return;if(e.key==='Backspace'){e.preventDefault();$('unload').click();}if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();$('undo').click();}if(e.ctrlKey&&e.key.toLowerCase()==='y'){e.preventDefault();$('redo').click();}});
  $('setFilter').innerHTML='<option value="">全部流派</option>'+['古典','流行','华丽','摇滚','爵士','通用'].map(s=>`<option>${s}</option>`).join('');
  $('applyUnlock').onclick=()=>{if(locked())return;try{const n=Number($('unlockCount').value);if(mode!=='test')throw Error('仅自由验证可手动设置测试格数');if(!Number.isInteger(n)||n<6||n>49)throw Error('格数须为6～49');checkpoint();const removed=E.manualUnlock(state,data,n);render();toast('已设为'+n+'格'+(removed.length?'；超出区域道具已回仓':''));}catch(e){toast(e.message);}};
  $('quickPreset').onchange=e=>{if(locked())return;if(e.target.value)preset(e.target.value);e.target.value='';};
  $('quickPreset').innerHTML='<option value="">载入参考布局</option>'+Object.keys(data.presets).map(n=>`<option>${esc(n)}</option>`).join('');
  loadMode(mode);
})();


