const assert=require('node:assert/strict'),E=require('./note-engine.js'),base=require('./data.json');
let checks=0;function test(name,fn){fn();checks++;console.log('PASS '+name);}
const copy=()=>E.clone(base);
function scene(entries,data=base){const s=E.newState(data,'test');s.unlocked=Array.from({length:49},(_,i)=>i);s.placed=entries.map(([id,x=0,y=0])=>({id,x,y}));return s;}
function run(entries,edit=()=>{},opts={}){const d=copy();edit(d);return E.performance(scene(entries,d),d,{seed:'verify',trace:true,...opts});}
function flat(d,q=1){for(const k of E.qualities)d.rules.noteWeights[k]=Array.from({length:5},(_,i)=>+(i===q));}
test('45 IDs implemented, complete six-level data',()=>{assert.equal(base.items.length,45);assert.deepEqual(base.items.map(i=>i.id).sort(),E.supported.sort());for(const i of base.items){assert.equal(i.base.length,6);assert.equal(i.effect.length,6);assert.equal(i.area,i.width*i.height);}});
test('empty bag and scores do not emit notes',()=>{assert.equal(run([]).total,0);assert.equal(run([['D01']]).totalNotes,0);});
test('20 pulses includes t10, excludes t0; no phantom score',()=>{const r=run([['G05']],d=>flat(d,0));assert.equal(r.regular,40);assert.equal(r.additional,0);assert.equal(r.N,40);assert.equal(r.preview,172.8);assert.equal(r.total,175);assert.equal(r.noteTrace[0].time,.5);assert.equal(r.noteTrace.at(-1).time,10);});
test('every level uses its own base/effect values',()=>{const s=scene([['G05']]);for(let lv=1;lv<=6;lv++){s.owned.G05.level=lv;const i=base.items.find(i=>i.id==='G05');assert(Math.abs(E.score(s,base).total-i.base[lv-1]*(1+i.effect[lv-1]/100))<1e-8);}});
test('layout bonuses add before multiplication; orthogonal not diagonal',()=>{const s=scene([['C01',0,0],['C03',3,0],['G08',6,0],['D01',0,2]]),r=E.score(s,base);assert(Math.abs(r.info.C01.total-960*1.30)<1e-8);assert(!E.adjacent({x:0,y:0,width:1,height:1},{x:1,y:1,width:1,height:1}));});
test('C02 violin group emits 4K per second (one and three)',()=>{assert.equal(run([['C02']]).stats.C02.regular,40);const r=run([['C02'],['C05',3],['B02',4]]);assert.equal(r.stats.C02.regular,120);assert.equal(r.preview,E.score(scene([['C02'],['C05',3],['B02',4]]),base).total);});
test('R03 faster clock and R04 concentrated clock',()=>{assert.equal(run([['R03']]).stats.R03.regular,100);assert.equal(run([['R04']]).stats.R04.regular,60);});
test('P01 copies adjacent green/blue; copies never recurse',()=>{const r=run([['P01'],['G05',2]],d=>flat(d,1));assert.equal(r.stats.G05.regular,40);assert.equal(r.stats.G05.additional,40);assert(r.noteTrace.filter(n=>n.source==='G05'&&n.extra).every(n=>n.coef===.6));assert.equal(r.stats.P01.additional,0);});
test('P02 blue table and highest-probability single copy selection',()=>{const r=run([['P01'],['P02',2]],d=>{flat(d,1);d.items.find(i=>i.id==='P02').effect.fill(100);});assert.equal(r.stats.P02.additional,80);assert(r.noteTrace.filter(n=>n.source==='P02'&&n.extra).every(n=>n.coef===1));assert.equal(r.effects.P01,undefined);});
test('H01 max2 each source batch; copies excluded from quota',()=>{const r=run([['H01']],d=>flat(d,1));assert.equal(r.stats.H01.qualities[2],40);assert.equal(r.stats.H01.qualities[1],80);});
test('H02 transforms blue additional once; J03 additional cannot recurse',()=>{const r=run([['H02'],['J03',1]],d=>{flat(d,1);d.items.find(i=>i.id==='H02').effect.fill(100);});assert.equal(r.stats.H02.qualities[2],80);assert.equal(r.stats.J03.additional,40);assert.equal(r.effects.J03,40);});
test('H03 fourth batch forces gold before jazz, is not a changed note',()=>{const r=run([['H03'],['J03',2]],d=>flat(d,1));assert.equal(r.stats.H03.qualities[3],20);assert.equal(r.stats.H03.changed,0);assert.equal(r.stats.J03.additional,0);});
test('J01 downshift happens before copy eligibility',()=>{const r=run([['J01',0,0],['P01',3,0],['G05',2,0]],d=>{flat(d,2);d.items.find(i=>i.id==='J01').effect.fill(0);});assert.equal(r.stats.G05.additional,40);assert(r.noteTrace.filter(n=>n.source==='G05').every(n=>n.quality===1&&n.down));});
test('J01/J02 modulation once; boundary unchanged not colored',()=>{const r=run([['J01'],['J02',2]],d=>{flat(d,4);d.items.find(i=>i.id==='J01').effect.fill(100);});assert.equal(r.stats.J02.changed,0);assert.equal(r.stats.J02.qualities[4],80);});
test('R05 window includes boundary and excludes own regular',()=>{const r=run([['R05']],d=>flat(d,1));assert.equal(r.regular,40);assert.equal(r.additional,30);assert.equal(r.timeline.length,10);assert.equal(r.noteTrace.filter(n=>n.extra).at(-1).time,10);});
test('B04 sees 8 additional and buffs next window only',()=>{const r=run([['B04',0,0],['P01',0,1],['G05',2,1]],d=>flat(d,1));assert(r.noteTrace.filter(n=>n.source==='B04'&&n.time<=1).every(n=>n.percent===0));assert(r.noteTrace.some(n=>n.source==='B04'&&n.time===1.5&&n.percent===10));});
test('Solo freezes regular clocks, two G gold batches; scores excluded from G',()=>{const r=run([['R02'],['G05',2],['D04',3]],d=>flat(d,1));assert.equal(r.G,6);assert.equal(r.stats.R02.regular,72);assert.equal(r.stats.G05.regular,36);assert.equal(r.stats.R02.additional,12);assert.deepEqual(r.events.filter(e=>e.type==='Solo出音').map(e=>e.time),[5.5,6]);assert(!r.noteTrace.some(n=>!n.extra&&n.time>5&&n.time<=6));});
test('surge preserves fractional clocks and pauses accumulation',()=>{const r=run([['R01'],['R03',4]],d=>{flat(d,1);d.rules.surgeThreshold=30;});assert(r.effects.R01>=1);assert(r.stats.R03.regular>100);const starts=r.events.filter(e=>e.type==='高潮开始');for(let i=1;i<starts.length;i++)assert(starts[i].time-starts[i-1].time>=1-1e-8);assert(r.noteTrace.every(n=>n.time<=10));});
test('fixed points after additive percentages',()=>{const r=run([['P01'],['G05',2],['P03',3],['P04',2,2]],d=>flat(d,1));const n=r.noteTrace.find(n=>n.source==='G05'&&n.extra);assert.equal(n.coef,.6);assert.equal(n.fixed,.2);assert(Math.abs(n.points-(1.4*.6*1.1+.2))<1e-8);});
test('seed reproducible and placement array ordering invariant',()=>{const s=scene(base.presets['爵士'].map(p=>[p.id,p.x,p.y]));const a=E.performance(s,base,{seed:'same'});s.placed.reverse();assert.deepEqual(E.performance(s,base,{seed:'same'}),a);assert.notEqual(E.performance(s,base,{seed:'different'}).N,a.N);});
test('ten reference layouts valid at all levels and deterministic',()=>{for(const [name,ps] of Object.entries(base.presets)){const s=scene([]);for(const p of ps){assert(E.validPlacement(s,base,p.id,p.x,p.y),name);s.placed.push(p);}for(const lv of [1,6]){for(const id in s.owned)s.owned[id].level=lv;const r=E.performance(s,base,{seed:name});assert(r.total>0);assert.equal(r.regular+r.additional,r.totalNotes);assert(Math.abs(Object.values(r.stats).reduce((n,s)=>n+s.score,0)-r.N)<1e-6);assert.equal(r.total,Math.floor(r.preview*(1+r.N/base.rules.noteDivisor)+1e-9));}}});
test('999 stamina, independent reward counters, duplicates upgrade one',()=>{const s=E.newState(base,'test');assert.equal(s.stamina,999);E.spend(s,base,5);assert.equal(s.stamina,994);assert.equal(s.unlockCredits,2);assert.equal(s.drawQueue.length,1);assert.equal(s.drawRemainder,2);const id=s.drawQueue[0].choices[0];E.choose(s,base,id);assert.equal(s.owned[id].level,2);});
test('draw #7 advanced; both modes have unique IDs, mixed mode not forced same',()=>{let mixed=0;for(const sameQualityDraw of [true,false]){const d=copy();d.rules.sameQualityDraw=sameQualityDraw;for(let i=1;i<=200;i++){const q=E.makeDraw(d,i,'draw'+i),qualities=new Set(q.choices.map(id=>d.items.find(x=>x.id===id).quality));assert.equal(q.advanced,i%7===0);assert.equal(new Set(q.choices).size,3);if(sameQualityDraw)assert.equal(qualities.size,1);else if(qualities.size>1)mixed++;}}assert(mixed>50);});
test('all effects exercised through solo/all-pair fixtures',()=>{const hit=new Set();for(const source of base.items){for(const target of base.items){if(source.id===target.id||source.height+target.height>7)continue;const d=copy();d.rules.surgeThreshold=10;const r=run([[source.id,0,0],[target.id,0,source.height]],x=>{x.rules.surgeThreshold=10;}, {seed:'coverage'});for(const id of Object.keys(r.effects))hit.add(id);}}for(const r of [run([['P01'],['R03',2]],d=>flat(d,1)),run([['B04'],['P02',0,1]],d=>{flat(d,1);d.items.find(i=>i.id==='P02').effect.fill(100);})])for(const id of Object.keys(r.effects))hit.add(id);for(const id of ['C01','C05','P01','P02','P03','P04','P05','H01','H02','H03','H04','H05','R01','R02','R03','R05','J01','J02','J03','J04','J05','B03','B04','B05','G02','G04','G07','G10','D02','D03','D04','D05'])assert(hit.has(id),'unexercised '+id);});
console.log(`${checks} rule groups passed`);



