const assert=require('node:assert/strict'),E=require('./note-engine.js'),P=require('./process-test.js'),d=require('./data.json');
const s=E.newState(d,'test');s.placed=[{id:'G05',x:0,y:0},{id:'P02',x:2,y:0},{id:'C01',x:0,y:3},{id:'D01',x:4,y:4}];
const before=JSON.stringify(s),a=P.plan(s,d,'A','test'),b=P.plan(s,d,'B','test');
assert.equal(a.attempts.length,120);assert(a.attempts.every(e=>Number.isInteger(e.time*4)&&e.time>=.25&&e.time<=10));assert(a.events.length>0&&a.events.length<120);assert.equal(a.lifetime,.5);assert.equal(a.duration,10);
console.log('PASS A: 40 independent attempts per instrument, no t0, .5s lifetime');
for(const plan of [a,b])for(const e of plan.events){const p=s.placed.find(p=>p.id===e.source),i=d.items.find(i=>i.id===p.id);assert.equal(e.notes.length,i.area);assert.equal(new Set(e.notes.map(n=>n.x+','+n.y)).size,i.area);for(const n of e.notes){assert(n.x>=p.x&&n.x<p.x+i.width&&n.y>=p.y&&n.y<p.y+i.height);const q=['绿','蓝','紫','金'].indexOf(i.quality);assert(n.quality>=q&&n.quality<=Math.min(4,q+2));}}
assert(!a.events.some(e=>e.source==='D01'));assert(!b.events.some(e=>e.source==='D01'));console.log('PASS one independently colored note per actual occupied cell; scores excluded');
const intervals=new Set();for(const id of ['G05','P02','C01']){let prev=0;for(const e of b.events.filter(e=>e.source===id)){const gap=e.time-prev;assert([.5,.75,1,1.25,1.5,1.75,2,2.25,2.5].includes(gap));intervals.add(gap);prev=e.time;}assert(prev<=10&&prev>=7.5);}assert(intervals.size>=3);assert(b.attempts.every(e=>e.emit));console.log('PASS B: independent rerolled intervals; emits every due time');
let misses=0,totalAttempts=0;const colors=[0,0,0],gold=[0,0,0];for(let seed=0;seed<600;seed++){const p=P.plan(s,d,'A','distribution'+seed);for(const e of p.attempts){totalAttempts++;if(!e.emit)misses++;}for(const e of p.events)for(const n of e.notes){if(e.source==='G05')colors[n.quality]++;if(e.source==='C01')gold[n.quality-3]++;}}
assert(Math.abs(misses/totalAttempts-.75)<.025);const total=colors.reduce((a,b)=>a+b,0);for(const [i,w] of [.8,.15,.05].entries())assert(Math.abs(colors[i]/total-w)<.025);assert.equal(gold[2],0);assert(Math.abs(gold[1]/(gold[0]+gold[1])-.2)<.025);console.log('PASS 600 seeds: 75% silence, 80/15/5 cell qualities, overflow clamps to red');
assert.deepEqual(P.plan(s,d,'A','test'),a);assert.notDeepEqual(P.plan(s,d,'A','other'),a);s.placed.reverse();assert.deepEqual(P.plan(s,d,'A','test'),a);s.placed.reverse();assert.equal(JSON.stringify(s),before);console.log('PASS reproducible seed, order independence, state and resources untouched');
assert.equal(P.plan({...s,placed:[]},d,'B').events.length,0);assert.throws(()=>P.plan(s,d,'C'));console.log('PASS empty layout and scheme validation');
console.log('6 process schedule groups passed');
